'use client';

import { useState, useCallback } from 'react';
import dynamic from 'next/dynamic';
import { useQuery } from '@tanstack/react-query';
import { uploadModel, listModels } from '@/lib/api';
import {
  Container,
  Typography,
  Box,
  Button,
  Paper,
  List,
  ListItemButton,
  ListItemText,
  Divider,
  CircularProgress,
  Alert,
  Chip,
  Stack,
} from '@mui/material';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';
import ViewInArIcon from '@mui/icons-material/ViewInAr';
import FolderOpenIcon from '@mui/icons-material/FolderOpen';

const ModelViewer = dynamic(() => import('@/components/ModelViewer'), {
  ssr: false,
  loading: () => (
    <Box
      sx={{
        width: '100%',
        height: 520,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        bgcolor: '#0f1117',
        borderRadius: 2,
      }}
    >
      <CircularProgress />
    </Box>
  ),
});

const BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://127.0.0.1:8000';

export default function ViewerPage() {
  const [activeModelUrl, setActiveModelUrl] = useState(null);
  const [activeModelName, setActiveModelName] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [uploadError, setUploadError] = useState(null);
  const [isDragging, setIsDragging] = useState(false);

  const { data: modelsData, refetch: refetchModels } = useQuery({
    queryKey: ['models'],
    queryFn: listModels,
  });

  const handleFile = useCallback(
    async (file) => {
      if (!file) return;
      const ext = file.name.split('.').pop().toLowerCase();
      if (!['glb', 'gltf'].includes(ext)) {
        setUploadError('Only .glb and .gltf files are supported');
        return;
      }
      setUploading(true);
      setUploadError(null);
      try {
        const result = await uploadModel(file);
        setActiveModelUrl(`${BASE_URL}${result.url}`);
        setActiveModelName(result.original_name);
        await refetchModels();
      } catch (e) {
        setUploadError(e.message || 'Upload failed');
      } finally {
        setUploading(false);
      }
    },
    [refetchModels],
  );

  const onFileChange = (e) => {
    const file = e.target.files?.[0];
    if (file) handleFile(file);
  };

  const onDrop = useCallback(
    (e) => {
      e.preventDefault();
      setIsDragging(false);
      const file = e.dataTransfer.files?.[0];
      if (file) handleFile(file);
    },
    [handleFile],
  );

  const onDragOver = (e) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const onDragLeave = () => setIsDragging(false);

  const models = modelsData ?? [];

  return (
    <Container maxWidth="xl" sx={{ mt: 4, pb: 6 }}>
      <Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 0.5 }}>
        <ViewInArIcon color="primary" fontSize="large" />
        <Typography variant="h4" fontWeight="bold">
          3D Model Viewer
        </Typography>
      </Stack>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
        Upload .glb or .gltf models exported from Agisoft Metashape to view them here.
      </Typography>

      {/* Upload drop zone */}
      <Paper
        onDrop={onDrop}
        onDragOver={onDragOver}
        onDragLeave={onDragLeave}
        sx={{
          p: 4,
          mb: 3,
          textAlign: 'center',
          border: '2px dashed',
          borderColor: isDragging ? 'primary.main' : 'divider',
          bgcolor: isDragging ? 'action.hover' : 'background.paper',
          transition: 'border-color 0.2s, background-color 0.2s',
        }}
      >
        <CloudUploadIcon sx={{ fontSize: 48, color: 'text.secondary', mb: 1 }} />
        <Typography variant="h6" gutterBottom>
          Drag & drop a .glb or .gltf file here
        </Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          Models generated by Agisoft Metashape — export as GLB before uploading
        </Typography>
        <Button
          variant="contained"
          component="label"
          disabled={uploading}
          startIcon={
            uploading ? <CircularProgress size={16} color="inherit" /> : <FolderOpenIcon />
          }
        >
          {uploading ? 'Uploading…' : 'Choose File'}
          <input type="file" hidden accept=".glb,.gltf" onChange={onFileChange} />
        </Button>
      </Paper>

      {uploadError && (
        <Alert severity="error" sx={{ mb: 2 }} onClose={() => setUploadError(null)}>
          {uploadError}
        </Alert>
      )}

      {/* Viewer + sidebar */}
      <Box sx={{ display: 'flex', gap: 2, alignItems: 'flex-start' }}>
        {/* 3D canvas */}
        <Box sx={{ flex: 1, minWidth: 0 }}>
          {activeModelUrl ? (
            <>
              <Stack direction="row" alignItems="center" spacing={1} sx={{ mb: 1 }}>
                <ViewInArIcon color="primary" fontSize="small" />
                <Typography variant="subtitle1" fontWeight="bold" noWrap>
                  {activeModelName}
                </Typography>
                <Chip label="Live" color="success" size="small" />
              </Stack>
              <ModelViewer url={activeModelUrl} />
              <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: 'block' }}>
                Left-drag to rotate &nbsp;·&nbsp; Scroll to zoom &nbsp;·&nbsp; Right-drag to pan
              </Typography>
            </>
          ) : (
            <Paper
              sx={{
                height: 520,
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
                bgcolor: '#0f1117',
                borderRadius: 2,
                gap: 1,
              }}
            >
              <ViewInArIcon sx={{ fontSize: 72, color: '#374151' }} />
              <Typography color="#6b7280" variant="body1">
                No model loaded
              </Typography>
              <Typography color="#4b5563" variant="body2">
                Upload a .glb file above to get started
              </Typography>
            </Paper>
          )}
        </Box>

        {/* Previously uploaded models sidebar */}
        {models.length > 0 && (
          <Paper sx={{ width: 280, flexShrink: 0 }}>
            <Typography variant="subtitle2" sx={{ p: 2, pb: 1, fontWeight: 'bold' }}>
              Uploaded Models ({models.length})
            </Typography>
            <Divider />
            <List dense sx={{ maxHeight: 520, overflow: 'auto', p: 0 }}>
              {models.map((model) => (
                <ListItemButton
                  key={model.filename}
                  selected={activeModelUrl === `${BASE_URL}${model.url}`}
                  onClick={() => {
                    setActiveModelUrl(`${BASE_URL}${model.url}`);
                    setActiveModelName(model.filename);
                  }}
                  sx={{ py: 1.5 }}
                >
                  <ListItemText
                    primary={model.filename}
                    secondary={`${(model.size_bytes / 1024).toFixed(1)} KB · ${new Date(
                      model.uploaded_at * 1000,
                    ).toLocaleDateString()}`}
                    primaryTypographyProps={{ noWrap: true, fontSize: '0.8rem' }}
                    secondaryTypographyProps={{ fontSize: '0.72rem' }}
                  />
                </ListItemButton>
              ))}
            </List>
          </Paper>
        )}
      </Box>
    </Container>
  );
}
